// Code generated by SQLBoiler 4.1.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Products      string
	PurchaseItems string
	Purchases     string
	Users         string
}{
	Products:      "products",
	PurchaseItems: "purchase_items",
	Purchases:     "purchases",
	Users:         "users",
}
