// Code generated by SQLBoiler 4.1.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testPurchaseItems(t *testing.T) {
	t.Parallel()

	query := PurchaseItems()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testPurchaseItemsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PurchaseItem{}
	if err = randomize.Struct(seed, o, purchaseItemDBTypes, true, purchaseItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PurchaseItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPurchaseItemsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PurchaseItem{}
	if err = randomize.Struct(seed, o, purchaseItemDBTypes, true, purchaseItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := PurchaseItems().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PurchaseItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPurchaseItemsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PurchaseItem{}
	if err = randomize.Struct(seed, o, purchaseItemDBTypes, true, purchaseItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PurchaseItemSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PurchaseItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPurchaseItemsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PurchaseItem{}
	if err = randomize.Struct(seed, o, purchaseItemDBTypes, true, purchaseItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := PurchaseItemExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if PurchaseItem exists: %s", err)
	}
	if !e {
		t.Errorf("Expected PurchaseItemExists to return true, but got false.")
	}
}

func testPurchaseItemsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PurchaseItem{}
	if err = randomize.Struct(seed, o, purchaseItemDBTypes, true, purchaseItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	purchaseItemFound, err := FindPurchaseItem(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if purchaseItemFound == nil {
		t.Error("want a record, got nil")
	}
}

func testPurchaseItemsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PurchaseItem{}
	if err = randomize.Struct(seed, o, purchaseItemDBTypes, true, purchaseItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = PurchaseItems().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testPurchaseItemsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PurchaseItem{}
	if err = randomize.Struct(seed, o, purchaseItemDBTypes, true, purchaseItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := PurchaseItems().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testPurchaseItemsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	purchaseItemOne := &PurchaseItem{}
	purchaseItemTwo := &PurchaseItem{}
	if err = randomize.Struct(seed, purchaseItemOne, purchaseItemDBTypes, false, purchaseItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}
	if err = randomize.Struct(seed, purchaseItemTwo, purchaseItemDBTypes, false, purchaseItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = purchaseItemOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = purchaseItemTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := PurchaseItems().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testPurchaseItemsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	purchaseItemOne := &PurchaseItem{}
	purchaseItemTwo := &PurchaseItem{}
	if err = randomize.Struct(seed, purchaseItemOne, purchaseItemDBTypes, false, purchaseItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}
	if err = randomize.Struct(seed, purchaseItemTwo, purchaseItemDBTypes, false, purchaseItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = purchaseItemOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = purchaseItemTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PurchaseItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func purchaseItemBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *PurchaseItem) error {
	*o = PurchaseItem{}
	return nil
}

func purchaseItemAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *PurchaseItem) error {
	*o = PurchaseItem{}
	return nil
}

func purchaseItemAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *PurchaseItem) error {
	*o = PurchaseItem{}
	return nil
}

func purchaseItemBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *PurchaseItem) error {
	*o = PurchaseItem{}
	return nil
}

func purchaseItemAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *PurchaseItem) error {
	*o = PurchaseItem{}
	return nil
}

func purchaseItemBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *PurchaseItem) error {
	*o = PurchaseItem{}
	return nil
}

func purchaseItemAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *PurchaseItem) error {
	*o = PurchaseItem{}
	return nil
}

func purchaseItemBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *PurchaseItem) error {
	*o = PurchaseItem{}
	return nil
}

func purchaseItemAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *PurchaseItem) error {
	*o = PurchaseItem{}
	return nil
}

func testPurchaseItemsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &PurchaseItem{}
	o := &PurchaseItem{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, purchaseItemDBTypes, false); err != nil {
		t.Errorf("Unable to randomize PurchaseItem object: %s", err)
	}

	AddPurchaseItemHook(boil.BeforeInsertHook, purchaseItemBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	purchaseItemBeforeInsertHooks = []PurchaseItemHook{}

	AddPurchaseItemHook(boil.AfterInsertHook, purchaseItemAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	purchaseItemAfterInsertHooks = []PurchaseItemHook{}

	AddPurchaseItemHook(boil.AfterSelectHook, purchaseItemAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	purchaseItemAfterSelectHooks = []PurchaseItemHook{}

	AddPurchaseItemHook(boil.BeforeUpdateHook, purchaseItemBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	purchaseItemBeforeUpdateHooks = []PurchaseItemHook{}

	AddPurchaseItemHook(boil.AfterUpdateHook, purchaseItemAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	purchaseItemAfterUpdateHooks = []PurchaseItemHook{}

	AddPurchaseItemHook(boil.BeforeDeleteHook, purchaseItemBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	purchaseItemBeforeDeleteHooks = []PurchaseItemHook{}

	AddPurchaseItemHook(boil.AfterDeleteHook, purchaseItemAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	purchaseItemAfterDeleteHooks = []PurchaseItemHook{}

	AddPurchaseItemHook(boil.BeforeUpsertHook, purchaseItemBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	purchaseItemBeforeUpsertHooks = []PurchaseItemHook{}

	AddPurchaseItemHook(boil.AfterUpsertHook, purchaseItemAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	purchaseItemAfterUpsertHooks = []PurchaseItemHook{}
}

func testPurchaseItemsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PurchaseItem{}
	if err = randomize.Struct(seed, o, purchaseItemDBTypes, true, purchaseItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PurchaseItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPurchaseItemsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PurchaseItem{}
	if err = randomize.Struct(seed, o, purchaseItemDBTypes, true); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(purchaseItemColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := PurchaseItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPurchaseItemToOneProductUsingProduct(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local PurchaseItem
	var foreign Product

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, purchaseItemDBTypes, true, purchaseItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, productDBTypes, false, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.ProductID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Product().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := PurchaseItemSlice{&local}
	if err = local.L.LoadProduct(ctx, tx, false, (*[]*PurchaseItem)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Product == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Product = nil
	if err = local.L.LoadProduct(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Product == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testPurchaseItemToOnePurchaseUsingPurchase(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local PurchaseItem
	var foreign Purchase

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, purchaseItemDBTypes, true, purchaseItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, purchaseDBTypes, false, purchaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.PurchaseID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Purchase().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := PurchaseItemSlice{&local}
	if err = local.L.LoadPurchase(ctx, tx, false, (*[]*PurchaseItem)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Purchase == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Purchase = nil
	if err = local.L.LoadPurchase(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Purchase == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testPurchaseItemToOneSetOpProductUsingProduct(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a PurchaseItem
	var b, c Product

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, purchaseItemDBTypes, false, strmangle.SetComplement(purchaseItemPrimaryKeyColumns, purchaseItemColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, productDBTypes, false, strmangle.SetComplement(productPrimaryKeyColumns, productColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, productDBTypes, false, strmangle.SetComplement(productPrimaryKeyColumns, productColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Product{&b, &c} {
		err = a.SetProduct(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Product != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.PurchaseItems[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.ProductID, x.ID) {
			t.Error("foreign key was wrong value", a.ProductID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.ProductID))
		reflect.Indirect(reflect.ValueOf(&a.ProductID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.ProductID, x.ID) {
			t.Error("foreign key was wrong value", a.ProductID, x.ID)
		}
	}
}

func testPurchaseItemToOneRemoveOpProductUsingProduct(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a PurchaseItem
	var b Product

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, purchaseItemDBTypes, false, strmangle.SetComplement(purchaseItemPrimaryKeyColumns, purchaseItemColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, productDBTypes, false, strmangle.SetComplement(productPrimaryKeyColumns, productColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetProduct(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveProduct(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Product().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Product != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.ProductID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.PurchaseItems) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testPurchaseItemToOneSetOpPurchaseUsingPurchase(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a PurchaseItem
	var b, c Purchase

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, purchaseItemDBTypes, false, strmangle.SetComplement(purchaseItemPrimaryKeyColumns, purchaseItemColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, purchaseDBTypes, false, strmangle.SetComplement(purchasePrimaryKeyColumns, purchaseColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, purchaseDBTypes, false, strmangle.SetComplement(purchasePrimaryKeyColumns, purchaseColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Purchase{&b, &c} {
		err = a.SetPurchase(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Purchase != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.PurchaseItems[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.PurchaseID, x.ID) {
			t.Error("foreign key was wrong value", a.PurchaseID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.PurchaseID))
		reflect.Indirect(reflect.ValueOf(&a.PurchaseID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.PurchaseID, x.ID) {
			t.Error("foreign key was wrong value", a.PurchaseID, x.ID)
		}
	}
}

func testPurchaseItemToOneRemoveOpPurchaseUsingPurchase(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a PurchaseItem
	var b Purchase

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, purchaseItemDBTypes, false, strmangle.SetComplement(purchaseItemPrimaryKeyColumns, purchaseItemColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, purchaseDBTypes, false, strmangle.SetComplement(purchasePrimaryKeyColumns, purchaseColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetPurchase(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemovePurchase(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Purchase().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Purchase != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.PurchaseID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.PurchaseItems) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testPurchaseItemsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PurchaseItem{}
	if err = randomize.Struct(seed, o, purchaseItemDBTypes, true, purchaseItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPurchaseItemsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PurchaseItem{}
	if err = randomize.Struct(seed, o, purchaseItemDBTypes, true, purchaseItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PurchaseItemSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPurchaseItemsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PurchaseItem{}
	if err = randomize.Struct(seed, o, purchaseItemDBTypes, true, purchaseItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := PurchaseItems().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	purchaseItemDBTypes = map[string]string{`ID`: `integer`, `PurchaseID`: `integer`, `ProductID`: `integer`, `Price`: `numeric`, `Quantity`: `integer`, `State`: `character varying`}
	_                   = bytes.MinRead
)

func testPurchaseItemsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(purchaseItemPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(purchaseItemAllColumns) == len(purchaseItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &PurchaseItem{}
	if err = randomize.Struct(seed, o, purchaseItemDBTypes, true, purchaseItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PurchaseItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, purchaseItemDBTypes, true, purchaseItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testPurchaseItemsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(purchaseItemAllColumns) == len(purchaseItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &PurchaseItem{}
	if err = randomize.Struct(seed, o, purchaseItemDBTypes, true, purchaseItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PurchaseItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, purchaseItemDBTypes, true, purchaseItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(purchaseItemAllColumns, purchaseItemPrimaryKeyColumns) {
		fields = purchaseItemAllColumns
	} else {
		fields = strmangle.SetComplement(
			purchaseItemAllColumns,
			purchaseItemPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := PurchaseItemSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testPurchaseItemsUpsert(t *testing.T) {
	t.Parallel()

	if len(purchaseItemAllColumns) == len(purchaseItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := PurchaseItem{}
	if err = randomize.Struct(seed, &o, purchaseItemDBTypes, true); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert PurchaseItem: %s", err)
	}

	count, err := PurchaseItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, purchaseItemDBTypes, false, purchaseItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PurchaseItem struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert PurchaseItem: %s", err)
	}

	count, err = PurchaseItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
