// Code generated by SQLBoiler 4.1.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Purchase is an object representing the database table.
type Purchase struct {
	ID        int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	Name      null.String `boil:"name" json:"name,omitempty" toml:"name" yaml:"name,omitempty"`
	Address   null.String `boil:"address" json:"address,omitempty" toml:"address" yaml:"address,omitempty"`
	State     null.String `boil:"state" json:"state,omitempty" toml:"state" yaml:"state,omitempty"`
	Zipcode   null.Int    `boil:"zipcode" json:"zipcode,omitempty" toml:"zipcode" yaml:"zipcode,omitempty"`
	UserID    null.Int    `boil:"user_id" json:"user_id,omitempty" toml:"user_id" yaml:"user_id,omitempty"`

	R *purchaseR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L purchaseL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PurchaseColumns = struct {
	ID        string
	CreatedAt string
	Name      string
	Address   string
	State     string
	Zipcode   string
	UserID    string
}{
	ID:        "id",
	CreatedAt: "created_at",
	Name:      "name",
	Address:   "address",
	State:     "state",
	Zipcode:   "zipcode",
	UserID:    "user_id",
}

// Generated where

var PurchaseWhere = struct {
	ID        whereHelperint
	CreatedAt whereHelpernull_Time
	Name      whereHelpernull_String
	Address   whereHelpernull_String
	State     whereHelpernull_String
	Zipcode   whereHelpernull_Int
	UserID    whereHelpernull_Int
}{
	ID:        whereHelperint{field: "\"purchases\".\"id\""},
	CreatedAt: whereHelpernull_Time{field: "\"purchases\".\"created_at\""},
	Name:      whereHelpernull_String{field: "\"purchases\".\"name\""},
	Address:   whereHelpernull_String{field: "\"purchases\".\"address\""},
	State:     whereHelpernull_String{field: "\"purchases\".\"state\""},
	Zipcode:   whereHelpernull_Int{field: "\"purchases\".\"zipcode\""},
	UserID:    whereHelpernull_Int{field: "\"purchases\".\"user_id\""},
}

// PurchaseRels is where relationship names are stored.
var PurchaseRels = struct {
	User          string
	PurchaseItems string
}{
	User:          "User",
	PurchaseItems: "PurchaseItems",
}

// purchaseR is where relationships are stored.
type purchaseR struct {
	User          *User             `boil:"User" json:"User" toml:"User" yaml:"User"`
	PurchaseItems PurchaseItemSlice `boil:"PurchaseItems" json:"PurchaseItems" toml:"PurchaseItems" yaml:"PurchaseItems"`
}

// NewStruct creates a new relationship struct
func (*purchaseR) NewStruct() *purchaseR {
	return &purchaseR{}
}

// purchaseL is where Load methods for each relationship are stored.
type purchaseL struct{}

var (
	purchaseAllColumns            = []string{"id", "created_at", "name", "address", "state", "zipcode", "user_id"}
	purchaseColumnsWithoutDefault = []string{"created_at", "name", "address", "state", "zipcode", "user_id"}
	purchaseColumnsWithDefault    = []string{"id"}
	purchasePrimaryKeyColumns     = []string{"id"}
)

type (
	// PurchaseSlice is an alias for a slice of pointers to Purchase.
	// This should generally be used opposed to []Purchase.
	PurchaseSlice []*Purchase
	// PurchaseHook is the signature for custom Purchase hook methods
	PurchaseHook func(context.Context, boil.ContextExecutor, *Purchase) error

	purchaseQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	purchaseType                 = reflect.TypeOf(&Purchase{})
	purchaseMapping              = queries.MakeStructMapping(purchaseType)
	purchasePrimaryKeyMapping, _ = queries.BindMapping(purchaseType, purchaseMapping, purchasePrimaryKeyColumns)
	purchaseInsertCacheMut       sync.RWMutex
	purchaseInsertCache          = make(map[string]insertCache)
	purchaseUpdateCacheMut       sync.RWMutex
	purchaseUpdateCache          = make(map[string]updateCache)
	purchaseUpsertCacheMut       sync.RWMutex
	purchaseUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var purchaseBeforeInsertHooks []PurchaseHook
var purchaseBeforeUpdateHooks []PurchaseHook
var purchaseBeforeDeleteHooks []PurchaseHook
var purchaseBeforeUpsertHooks []PurchaseHook

var purchaseAfterInsertHooks []PurchaseHook
var purchaseAfterSelectHooks []PurchaseHook
var purchaseAfterUpdateHooks []PurchaseHook
var purchaseAfterDeleteHooks []PurchaseHook
var purchaseAfterUpsertHooks []PurchaseHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Purchase) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range purchaseBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Purchase) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range purchaseBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Purchase) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range purchaseBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Purchase) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range purchaseBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Purchase) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range purchaseAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Purchase) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range purchaseAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Purchase) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range purchaseAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Purchase) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range purchaseAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Purchase) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range purchaseAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPurchaseHook registers your hook function for all future operations.
func AddPurchaseHook(hookPoint boil.HookPoint, purchaseHook PurchaseHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		purchaseBeforeInsertHooks = append(purchaseBeforeInsertHooks, purchaseHook)
	case boil.BeforeUpdateHook:
		purchaseBeforeUpdateHooks = append(purchaseBeforeUpdateHooks, purchaseHook)
	case boil.BeforeDeleteHook:
		purchaseBeforeDeleteHooks = append(purchaseBeforeDeleteHooks, purchaseHook)
	case boil.BeforeUpsertHook:
		purchaseBeforeUpsertHooks = append(purchaseBeforeUpsertHooks, purchaseHook)
	case boil.AfterInsertHook:
		purchaseAfterInsertHooks = append(purchaseAfterInsertHooks, purchaseHook)
	case boil.AfterSelectHook:
		purchaseAfterSelectHooks = append(purchaseAfterSelectHooks, purchaseHook)
	case boil.AfterUpdateHook:
		purchaseAfterUpdateHooks = append(purchaseAfterUpdateHooks, purchaseHook)
	case boil.AfterDeleteHook:
		purchaseAfterDeleteHooks = append(purchaseAfterDeleteHooks, purchaseHook)
	case boil.AfterUpsertHook:
		purchaseAfterUpsertHooks = append(purchaseAfterUpsertHooks, purchaseHook)
	}
}

// One returns a single purchase record from the query.
func (q purchaseQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Purchase, error) {
	o := &Purchase{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for purchases")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Purchase records from the query.
func (q purchaseQuery) All(ctx context.Context, exec boil.ContextExecutor) (PurchaseSlice, error) {
	var o []*Purchase

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Purchase slice")
	}

	if len(purchaseAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Purchase records in the query.
func (q purchaseQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count purchases rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q purchaseQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if purchases exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *Purchase) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	query := Users(queryMods...)
	queries.SetFrom(query.Query, "\"users\"")

	return query
}

// PurchaseItems retrieves all the purchase_item's PurchaseItems with an executor.
func (o *Purchase) PurchaseItems(mods ...qm.QueryMod) purchaseItemQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"purchase_items\".\"purchase_id\"=?", o.ID),
	)

	query := PurchaseItems(queryMods...)
	queries.SetFrom(query.Query, "\"purchase_items\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"purchase_items\".*"})
	}

	return query
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (purchaseL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybePurchase interface{}, mods queries.Applicator) error {
	var slice []*Purchase
	var object *Purchase

	if singular {
		object = maybePurchase.(*Purchase)
	} else {
		slice = *maybePurchase.(*[]*Purchase)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &purchaseR{}
		}
		if !queries.IsNil(object.UserID) {
			args = append(args, object.UserID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &purchaseR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.UserID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.UserID) {
				args = append(args, obj.UserID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(purchaseAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.Purchases = append(foreign.R.Purchases, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.UserID, foreign.ID) {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.Purchases = append(foreign.R.Purchases, local)
				break
			}
		}
	}

	return nil
}

// LoadPurchaseItems allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (purchaseL) LoadPurchaseItems(ctx context.Context, e boil.ContextExecutor, singular bool, maybePurchase interface{}, mods queries.Applicator) error {
	var slice []*Purchase
	var object *Purchase

	if singular {
		object = maybePurchase.(*Purchase)
	} else {
		slice = *maybePurchase.(*[]*Purchase)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &purchaseR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &purchaseR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`purchase_items`),
		qm.WhereIn(`purchase_items.purchase_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load purchase_items")
	}

	var resultSlice []*PurchaseItem
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice purchase_items")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on purchase_items")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for purchase_items")
	}

	if len(purchaseItemAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.PurchaseItems = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &purchaseItemR{}
			}
			foreign.R.Purchase = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.PurchaseID) {
				local.R.PurchaseItems = append(local.R.PurchaseItems, foreign)
				if foreign.R == nil {
					foreign.R = &purchaseItemR{}
				}
				foreign.R.Purchase = local
				break
			}
		}
	}

	return nil
}

// SetUser of the purchase to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Purchases.
func (o *Purchase) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"purchases\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, purchasePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.UserID, related.ID)
	if o.R == nil {
		o.R = &purchaseR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			Purchases: PurchaseSlice{o},
		}
	} else {
		related.R.Purchases = append(related.R.Purchases, o)
	}

	return nil
}

// RemoveUser relationship.
// Sets o.R.User to nil.
// Removes o from all passed in related items' relationships struct (Optional).
func (o *Purchase) RemoveUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.UserID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("user_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.User = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.Purchases {
		if queries.Equal(o.UserID, ri.UserID) {
			continue
		}

		ln := len(related.R.Purchases)
		if ln > 1 && i < ln-1 {
			related.R.Purchases[i] = related.R.Purchases[ln-1]
		}
		related.R.Purchases = related.R.Purchases[:ln-1]
		break
	}
	return nil
}

// AddPurchaseItems adds the given related objects to the existing relationships
// of the purchase, optionally inserting them as new records.
// Appends related to o.R.PurchaseItems.
// Sets related.R.Purchase appropriately.
func (o *Purchase) AddPurchaseItems(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*PurchaseItem) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.PurchaseID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"purchase_items\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"purchase_id"}),
				strmangle.WhereClause("\"", "\"", 2, purchaseItemPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.PurchaseID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &purchaseR{
			PurchaseItems: related,
		}
	} else {
		o.R.PurchaseItems = append(o.R.PurchaseItems, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &purchaseItemR{
				Purchase: o,
			}
		} else {
			rel.R.Purchase = o
		}
	}
	return nil
}

// SetPurchaseItems removes all previously related items of the
// purchase replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Purchase's PurchaseItems accordingly.
// Replaces o.R.PurchaseItems with related.
// Sets related.R.Purchase's PurchaseItems accordingly.
func (o *Purchase) SetPurchaseItems(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*PurchaseItem) error {
	query := "update \"purchase_items\" set \"purchase_id\" = null where \"purchase_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.PurchaseItems {
			queries.SetScanner(&rel.PurchaseID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Purchase = nil
		}

		o.R.PurchaseItems = nil
	}
	return o.AddPurchaseItems(ctx, exec, insert, related...)
}

// RemovePurchaseItems relationships from objects passed in.
// Removes related items from R.PurchaseItems (uses pointer comparison, removal does not keep order)
// Sets related.R.Purchase.
func (o *Purchase) RemovePurchaseItems(ctx context.Context, exec boil.ContextExecutor, related ...*PurchaseItem) error {
	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.PurchaseID, nil)
		if rel.R != nil {
			rel.R.Purchase = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("purchase_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.PurchaseItems {
			if rel != ri {
				continue
			}

			ln := len(o.R.PurchaseItems)
			if ln > 1 && i < ln-1 {
				o.R.PurchaseItems[i] = o.R.PurchaseItems[ln-1]
			}
			o.R.PurchaseItems = o.R.PurchaseItems[:ln-1]
			break
		}
	}

	return nil
}

// Purchases retrieves all the records using an executor.
func Purchases(mods ...qm.QueryMod) purchaseQuery {
	mods = append(mods, qm.From("\"purchases\""))
	return purchaseQuery{NewQuery(mods...)}
}

// FindPurchase retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPurchase(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*Purchase, error) {
	purchaseObj := &Purchase{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"purchases\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, purchaseObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from purchases")
	}

	return purchaseObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Purchase) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no purchases provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(purchaseColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	purchaseInsertCacheMut.RLock()
	cache, cached := purchaseInsertCache[key]
	purchaseInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			purchaseAllColumns,
			purchaseColumnsWithDefault,
			purchaseColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(purchaseType, purchaseMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(purchaseType, purchaseMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"purchases\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"purchases\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into purchases")
	}

	if !cached {
		purchaseInsertCacheMut.Lock()
		purchaseInsertCache[key] = cache
		purchaseInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Purchase.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Purchase) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	purchaseUpdateCacheMut.RLock()
	cache, cached := purchaseUpdateCache[key]
	purchaseUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			purchaseAllColumns,
			purchasePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update purchases, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"purchases\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, purchasePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(purchaseType, purchaseMapping, append(wl, purchasePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update purchases row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for purchases")
	}

	if !cached {
		purchaseUpdateCacheMut.Lock()
		purchaseUpdateCache[key] = cache
		purchaseUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q purchaseQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for purchases")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for purchases")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PurchaseSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), purchasePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"purchases\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, purchasePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in purchase slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all purchase")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Purchase) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no purchases provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(purchaseColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	purchaseUpsertCacheMut.RLock()
	cache, cached := purchaseUpsertCache[key]
	purchaseUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			purchaseAllColumns,
			purchaseColumnsWithDefault,
			purchaseColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			purchaseAllColumns,
			purchasePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert purchases, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(purchasePrimaryKeyColumns))
			copy(conflict, purchasePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"purchases\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(purchaseType, purchaseMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(purchaseType, purchaseMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert purchases")
	}

	if !cached {
		purchaseUpsertCacheMut.Lock()
		purchaseUpsertCache[key] = cache
		purchaseUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Purchase record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Purchase) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Purchase provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), purchasePrimaryKeyMapping)
	sql := "DELETE FROM \"purchases\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from purchases")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for purchases")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q purchaseQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no purchaseQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from purchases")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for purchases")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PurchaseSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(purchaseBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), purchasePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"purchases\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, purchasePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from purchase slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for purchases")
	}

	if len(purchaseAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Purchase) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPurchase(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PurchaseSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PurchaseSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), purchasePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"purchases\".* FROM \"purchases\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, purchasePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PurchaseSlice")
	}

	*o = slice

	return nil
}

// PurchaseExists checks if the Purchase row exists.
func PurchaseExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"purchases\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if purchases exists")
	}

	return exists, nil
}
