// Code generated by SQLBoiler 4.1.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testPurchases(t *testing.T) {
	t.Parallel()

	query := Purchases()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testPurchasesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Purchase{}
	if err = randomize.Struct(seed, o, purchaseDBTypes, true, purchaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Purchases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPurchasesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Purchase{}
	if err = randomize.Struct(seed, o, purchaseDBTypes, true, purchaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Purchases().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Purchases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPurchasesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Purchase{}
	if err = randomize.Struct(seed, o, purchaseDBTypes, true, purchaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PurchaseSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Purchases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPurchasesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Purchase{}
	if err = randomize.Struct(seed, o, purchaseDBTypes, true, purchaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := PurchaseExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Purchase exists: %s", err)
	}
	if !e {
		t.Errorf("Expected PurchaseExists to return true, but got false.")
	}
}

func testPurchasesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Purchase{}
	if err = randomize.Struct(seed, o, purchaseDBTypes, true, purchaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	purchaseFound, err := FindPurchase(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if purchaseFound == nil {
		t.Error("want a record, got nil")
	}
}

func testPurchasesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Purchase{}
	if err = randomize.Struct(seed, o, purchaseDBTypes, true, purchaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Purchases().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testPurchasesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Purchase{}
	if err = randomize.Struct(seed, o, purchaseDBTypes, true, purchaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Purchases().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testPurchasesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	purchaseOne := &Purchase{}
	purchaseTwo := &Purchase{}
	if err = randomize.Struct(seed, purchaseOne, purchaseDBTypes, false, purchaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}
	if err = randomize.Struct(seed, purchaseTwo, purchaseDBTypes, false, purchaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = purchaseOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = purchaseTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Purchases().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testPurchasesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	purchaseOne := &Purchase{}
	purchaseTwo := &Purchase{}
	if err = randomize.Struct(seed, purchaseOne, purchaseDBTypes, false, purchaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}
	if err = randomize.Struct(seed, purchaseTwo, purchaseDBTypes, false, purchaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = purchaseOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = purchaseTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Purchases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func purchaseBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Purchase) error {
	*o = Purchase{}
	return nil
}

func purchaseAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Purchase) error {
	*o = Purchase{}
	return nil
}

func purchaseAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Purchase) error {
	*o = Purchase{}
	return nil
}

func purchaseBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Purchase) error {
	*o = Purchase{}
	return nil
}

func purchaseAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Purchase) error {
	*o = Purchase{}
	return nil
}

func purchaseBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Purchase) error {
	*o = Purchase{}
	return nil
}

func purchaseAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Purchase) error {
	*o = Purchase{}
	return nil
}

func purchaseBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Purchase) error {
	*o = Purchase{}
	return nil
}

func purchaseAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Purchase) error {
	*o = Purchase{}
	return nil
}

func testPurchasesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Purchase{}
	o := &Purchase{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, purchaseDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Purchase object: %s", err)
	}

	AddPurchaseHook(boil.BeforeInsertHook, purchaseBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	purchaseBeforeInsertHooks = []PurchaseHook{}

	AddPurchaseHook(boil.AfterInsertHook, purchaseAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	purchaseAfterInsertHooks = []PurchaseHook{}

	AddPurchaseHook(boil.AfterSelectHook, purchaseAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	purchaseAfterSelectHooks = []PurchaseHook{}

	AddPurchaseHook(boil.BeforeUpdateHook, purchaseBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	purchaseBeforeUpdateHooks = []PurchaseHook{}

	AddPurchaseHook(boil.AfterUpdateHook, purchaseAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	purchaseAfterUpdateHooks = []PurchaseHook{}

	AddPurchaseHook(boil.BeforeDeleteHook, purchaseBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	purchaseBeforeDeleteHooks = []PurchaseHook{}

	AddPurchaseHook(boil.AfterDeleteHook, purchaseAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	purchaseAfterDeleteHooks = []PurchaseHook{}

	AddPurchaseHook(boil.BeforeUpsertHook, purchaseBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	purchaseBeforeUpsertHooks = []PurchaseHook{}

	AddPurchaseHook(boil.AfterUpsertHook, purchaseAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	purchaseAfterUpsertHooks = []PurchaseHook{}
}

func testPurchasesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Purchase{}
	if err = randomize.Struct(seed, o, purchaseDBTypes, true, purchaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Purchases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPurchasesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Purchase{}
	if err = randomize.Struct(seed, o, purchaseDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(purchaseColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Purchases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPurchaseToManyPurchaseItems(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Purchase
	var b, c PurchaseItem

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, purchaseDBTypes, true, purchaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, purchaseItemDBTypes, false, purchaseItemColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, purchaseItemDBTypes, false, purchaseItemColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.PurchaseID, a.ID)
	queries.Assign(&c.PurchaseID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.PurchaseItems().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.PurchaseID, b.PurchaseID) {
			bFound = true
		}
		if queries.Equal(v.PurchaseID, c.PurchaseID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := PurchaseSlice{&a}
	if err = a.L.LoadPurchaseItems(ctx, tx, false, (*[]*Purchase)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.PurchaseItems); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.PurchaseItems = nil
	if err = a.L.LoadPurchaseItems(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.PurchaseItems); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testPurchaseToManyAddOpPurchaseItems(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Purchase
	var b, c, d, e PurchaseItem

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, purchaseDBTypes, false, strmangle.SetComplement(purchasePrimaryKeyColumns, purchaseColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*PurchaseItem{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, purchaseItemDBTypes, false, strmangle.SetComplement(purchaseItemPrimaryKeyColumns, purchaseItemColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*PurchaseItem{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddPurchaseItems(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.PurchaseID) {
			t.Error("foreign key was wrong value", a.ID, first.PurchaseID)
		}
		if !queries.Equal(a.ID, second.PurchaseID) {
			t.Error("foreign key was wrong value", a.ID, second.PurchaseID)
		}

		if first.R.Purchase != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Purchase != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.PurchaseItems[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.PurchaseItems[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.PurchaseItems().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testPurchaseToManySetOpPurchaseItems(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Purchase
	var b, c, d, e PurchaseItem

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, purchaseDBTypes, false, strmangle.SetComplement(purchasePrimaryKeyColumns, purchaseColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*PurchaseItem{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, purchaseItemDBTypes, false, strmangle.SetComplement(purchaseItemPrimaryKeyColumns, purchaseItemColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetPurchaseItems(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.PurchaseItems().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetPurchaseItems(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.PurchaseItems().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.PurchaseID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.PurchaseID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.PurchaseID) {
		t.Error("foreign key was wrong value", a.ID, d.PurchaseID)
	}
	if !queries.Equal(a.ID, e.PurchaseID) {
		t.Error("foreign key was wrong value", a.ID, e.PurchaseID)
	}

	if b.R.Purchase != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Purchase != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Purchase != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Purchase != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.PurchaseItems[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.PurchaseItems[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testPurchaseToManyRemoveOpPurchaseItems(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Purchase
	var b, c, d, e PurchaseItem

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, purchaseDBTypes, false, strmangle.SetComplement(purchasePrimaryKeyColumns, purchaseColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*PurchaseItem{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, purchaseItemDBTypes, false, strmangle.SetComplement(purchaseItemPrimaryKeyColumns, purchaseItemColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddPurchaseItems(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.PurchaseItems().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemovePurchaseItems(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.PurchaseItems().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.PurchaseID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.PurchaseID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Purchase != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Purchase != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Purchase != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Purchase != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.PurchaseItems) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.PurchaseItems[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.PurchaseItems[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testPurchaseToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Purchase
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, purchaseDBTypes, true, purchaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.UserID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := PurchaseSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*Purchase)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testPurchaseToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Purchase
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, purchaseDBTypes, false, strmangle.SetComplement(purchasePrimaryKeyColumns, purchaseColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Purchases[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.UserID, x.ID) {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.UserID, x.ID) {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testPurchaseToOneRemoveOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Purchase
	var b User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, purchaseDBTypes, false, strmangle.SetComplement(purchasePrimaryKeyColumns, purchaseColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetUser(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveUser(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.User().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.User != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.UserID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.Purchases) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testPurchasesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Purchase{}
	if err = randomize.Struct(seed, o, purchaseDBTypes, true, purchaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPurchasesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Purchase{}
	if err = randomize.Struct(seed, o, purchaseDBTypes, true, purchaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PurchaseSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPurchasesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Purchase{}
	if err = randomize.Struct(seed, o, purchaseDBTypes, true, purchaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Purchases().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	purchaseDBTypes = map[string]string{`ID`: `integer`, `CreatedAt`: `timestamp with time zone`, `Name`: `character varying`, `Address`: `character varying`, `State`: `character varying`, `Zipcode`: `integer`, `UserID`: `integer`}
	_               = bytes.MinRead
)

func testPurchasesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(purchasePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(purchaseAllColumns) == len(purchasePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Purchase{}
	if err = randomize.Struct(seed, o, purchaseDBTypes, true, purchaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Purchases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, purchaseDBTypes, true, purchasePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testPurchasesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(purchaseAllColumns) == len(purchasePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Purchase{}
	if err = randomize.Struct(seed, o, purchaseDBTypes, true, purchaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Purchases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, purchaseDBTypes, true, purchasePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(purchaseAllColumns, purchasePrimaryKeyColumns) {
		fields = purchaseAllColumns
	} else {
		fields = strmangle.SetComplement(
			purchaseAllColumns,
			purchasePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := PurchaseSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testPurchasesUpsert(t *testing.T) {
	t.Parallel()

	if len(purchaseAllColumns) == len(purchasePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Purchase{}
	if err = randomize.Struct(seed, &o, purchaseDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Purchase: %s", err)
	}

	count, err := Purchases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, purchaseDBTypes, false, purchasePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Purchase struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Purchase: %s", err)
	}

	count, err = Purchases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
